---
name: Build and publish to Puppet Forge

on:
 push:
  tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Technical implemntation notes:
    #
    # - The latest ref is stored in $GITHUB_REF as 'refs/tags/<tag_name>'
    # - ${GITHUB_REF:10} is an obscure shell expansion syntax to lop off the
    #   'refs/tags/' prefix
    #
    - name: Get latest tag
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF:10}
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        ref: ${{ steps.vars.outputs.tag }}
    - run: 'echo "== LATEST TAG:  ${{ steps.vars.outputs.tag }}"'
#    - name: Build and publish module
#      uses: barnumbirr/action-forge-publish@v2.3.0
#      env:
#       FORGE_API_KEY: ${{ secrets.FORGE_API_KEY }}
#       REPOSITORY_URL: https://forgeapi.puppet.com/v3/releases
#
