# NOTES
# ------------------------------------------------------------------------------
# It would be nice if we could use an expression to set the default value of
# `github.event.inputs.branch` to the the repository's current default branch,
#  so the defaults always work, regardless of the whether it's `master`,
# `main`, or `fred`.
#
# Unfortunately, an expression like `${{ github.repository.default_branch }}`
# doesn't evaluate within `workflow_dispatch.inputs.*.default`, and the
# [`$default-branch` macro][1] only works in workflow **templates**.
#
# FIXME: When we implement [default branch renaming][2], this default MUST
#        be updated.
#
# [1]: https://github.blog/changelog/2020-07-22-github-actions-better-support-for-alternative-default-branch-names/
# [2]: https://github.com/github/renaming/
---
name: Prepare release
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Git branch to release'
        required: true
        default: master  # FIXME: ensure this is the correct branch (See NOTES)
      generate_docs:
        description: 'Generate documentation'
        required: true
        default: true
      build_artifacts:
        description: 'Build artifact'
        required: true
        default: true

jobs:
  generate-docs:
    name: "Generate Documentation"
    if: ${{ github.event.inputs.generate_docs }}
    runs-on: ubuntu-18.04
    env:
      PUPPET_VERSION: "~> 6"
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch}}
          clean: true
      - name: "Install Ruby ${{matrix.puppet.ruby_version}}"
        uses: ruby/setup-ruby@v1  # ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
        with:
          ruby-version: 2.5
          bundler-cache: true
      - run: 'bundle exec rake strings:generate:reference'
      - name: 'Set up git user & remote'
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"
          git remote add github "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@${GITHUB_SERVER_URL#*://}/${GITHUB_REPOSITORY}.git"
      - name: 'Commit REFERENCE.md'
        run: |
          git add REFERENCE.md
          git commit -m "Generate REFERENCE.md"
      - name: 'Commit REFERENCE.md'
        run: |
          git add REFERENCE.md
          git commit -m "Generate REFERENCE.md"



