
name: CI

# Controls when the action will run.
on:
  pull_request_target: {}
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:   
  demo:
    name: "Demo"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v3
      id: set-result
      with:
        script: return "Hello!"
        result-encoding: string
    - name: Get result
      run: echo "${{steps.set-result.outputs.result}}"
